using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Common.Models
{
    public static class Recipe
    {
        public static Int64 recipe_id;
        public static string number_recipe;
        public static DateTime date_recipe;
        public static string esf_od;
        public static string esf_oi;
        public static string cil_od;
        public static string cil_oi;
        public static string eje_od;
        public static string eje_oi;
        public static string adic_od;
        public static string adic_oi;
        public static string esf_od_recipe;
        public static string esf_oi_recipe;
        public static string cil_od_recipe;
        public static string cil_oi_recipe;
        public static string eje_od_recipe;
        public static string eje_oi_recipe;
        public static string adic_od_recipe;
        public static string adic_oi_recipe;
        public static string altob_od_recipe;
        public static string altob_oi_recipe;
        public static string altpu_od_recipe;
        public static string altpu_oi_recipe;
        public static string dplej_od_recipe;
        public static string dplej_oi_recipe;
        public static string dpcer_od_recipe;
        public static string dpcer_oi_recipe;
        public static string base_od_recipe;
        public static string base_oi_recipe;
        public static string lensometry_notes;
        public static Int64 ring_id;
        public static Int64 glasses_id;
        public static bool comp;
        public static bool sa;
        public static bool aa;
        public static bool ar;
        public static bool process;
        public static int quantity;
        public static string value;
        public static bool hypertension;
        public static bool diabetes;
        public static bool cataract;
        public static bool pterigion;
        public static bool irritation;
        public static bool sleepiness;
        public static bool burning;
        public static bool headache;
        public static bool itch;
        public static bool tearing;
        public static string eye_movementes;
        public static string ophthalmoscopy;
        public static string eye_adnexa;
        public static string hirsscheberg_test;
        public static string retinoscopy;
        public static Int64 laboratory_id;
        public static DateTime shipping_date;
        public static DateTime admission_date;
        public static DateTime delivery_date;
        public static Int64 optomestrist_id;
        public static Int64 consultant_id;
        public static Int64 client_id;
        public static Int32 client_age;
        public static string invoice_laboratory;
        public static string date_invoice_laboratory;
        public static string value_invoice_laboratory;
        public static string notes;
        public static string client_name;
        public static string client_lastname;
        public static string company_name;
        public static string ring;
        public static string glasses;
        public static string laboratory;
        public static string optometryst;
        public static string seller;
    }
}
